# Generated by Django 2.2 on 2022-10-19 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2000)),
                ('Post_date', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 9, 4, 57, 4401, tzinfo=utc))),
            ],
        ),
    ]
