# Generated by Django 4.0.8 on 2022-11-09 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 9, 2, 33, 658911, tzinfo=utc)),
        ),
    ]
