# Generated by Django 4.0.8 on 2022-12-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='static/img/product'),
        ),
    ]
