# Generated by Django 4.0.8 on 2022-12-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_image_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
