# Generated by Django 4.0.8 on 2022-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Admin_ID', max_length=5)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Username', max_length=10)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=10)),
                ('fname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fname', max_length=7)),
                ('middle_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Middle_name', max_length=7, null=True)),
                ('lname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lname', max_length=7)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=30, null=True)),
                ('phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=10)),
                ('authority', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Authority', max_length=10)),
            ],
            options={
                'db_table': '[management].[administrator]',
                'managed': False,
            },
        ),
    ]
