# Generated by Django 4.0.8 on 2022-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(db_column='Cart_ID')),
                ('total_price', models.FloatField(db_column='Total_price')),
                ('customer_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Customer_ID', max_length=5, null=True)),
            ],
            options={
                'db_table': '[service].[cart]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_column='Product_ID')),
                ('cart_id', models.IntegerField(db_column='Cart_ID')),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': '[service].[contain]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Customer_ID', max_length=5)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Username', max_length=10)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=10)),
                ('fname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fname', max_length=7)),
                ('middle_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Middle_name', max_length=7, null=True)),
                ('lname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lname', max_length=7)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=30, null=True)),
                ('phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=10)),
                ('address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=40)),
                ('birthdate', models.DateField(blank=True, db_column='Birthdate', null=True)),
            ],
            options={
                'db_table': '[service].[customer]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Customer_ID', max_length=5)),
                ('product_id', models.IntegerField(db_column='Product_ID')),
                ('content', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Content', null=True)),
                ('star', models.IntegerField(db_column='Star')),
                ('datepost', models.DateField(db_column='Datepost')),
            ],
            options={
                'db_table': '[service].[feedback]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Order_ID', max_length=5)),
                ('order_date', models.DateField(db_column='Order_date')),
                ('discount', models.FloatField(blank=True, db_column='Discount', null=True)),
                ('total_price', models.FloatField(db_column='Total_price')),
                ('delivery', models.BooleanField(blank=True, db_column='Delivery', null=True)),
                ('cart_id', models.IntegerField(blank=True, db_column='Cart_ID', null=True)),
            ],
            options={
                'db_table': '[service].[orders]',
                'managed': False,
            },
        ),
    ]
